### ISSUE TITLE
Oinkmaster failed returning 65280

### ISSUE THREAD

**Issue by tuttimann** [timfprogs/ipfidsupdate#2]
I've enabled automatic updates every hour and every hour I get the error message "Oinkmaster failed returning 65280" 4 times in the Logs.
The number of activated rules didn't change either.
What is this error message about and what can I do to fix this?

**Comment by timfprogs** [comment]
The most likely reason is that the files in /etc/snort/rules aren't all writeable by oinkmaster.  The should be owned by nobody and have permissions 0644.

If that doesn't fix the problem, try running /usr/local/bin/ids0update.pl from the command line and look for any error messages.

**Comment by tuttimann** [comment]
> The most likely reason is that the files in /etc/snort/rules aren't all writeable by oinkmaster. The should be owned by nobody and have permissions 0644.
> 
> If that doesn't fix the problem, try running /usr/local/bin/ids0update.pl from the command line and look for any error messages.

This fixed it for me, thanks 👍
